In [45]:
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [46]:
df = pd.read_csv('../data/ppr-group-25200353-train-geocoded.csv')
df.head()

,date_of_sale,address,county,price,not_full_market_price,vat_exclusive,property_description,mapbox_query,latitude,longitude,confidence,feature_type,match_code,geometry,index_right,cso_lea
0,2016-02-29,"APT 14, RUSSELL COURT, FELTRIM RD",Dublin,118487.0,No,No,Second-Hand Dwelling house /Apartment,"RUSSELL COURT, FELTRIM RD, CO. DUBLIN",53.433318,-6.177927,none,street,{},POINT (-6.177927 53.433318),86.0,HOWTH-MALAHIDE
1,2016-07-08,"19 PARK VILLAS, DEMESNE RD, DUNDALK",Louth,222000.0,No,No,Second-Hand Dwelling house /Apartment,"19 PARK VILLAS, DEMESNE RD, DUNDALK, CO. LOUTH",54.003768,-6.406065,high,address,"{""address_number"": ""matched"", ""street"": ""match...",POINT (-6.406065 54.003768),66.0,DUNDALK-CARLINGFORD
2,2016-04-15,"No 2 The Grove, Cahereen Heights, Castleisland",Kerry,123348.0,No,Yes,New Dwelling house /Apartment,"THE GROVE, CAHEREEN HEIGHTS, CASTLEISLAND, CO....",52.221088,-9.468242,none,street,{},POINT (-9.468242 52.221088),43.0,CASTLEISLAND
3,2016-12-21,"APT 4 BLOCK 6, WOODFORD, WHEATON HALL",Louth,115000.0,No,No,Second-Hand Dwelling house /Apartment,"BLOCK 6, WOODFORD, WHEATON HALL, CO. LOUTH",53.050891,-8.399598,low,address,"{""address_number"": ""matched"", ""street"": ""unmat...",POINT (-8.399598 53.050891),109.0,LOUGHREA
4,2016-10-11,"18 GERALDINE ST, DUBLIN 7, DUBLIN",Dublin,225500.0,No,No,Second-Hand Dwelling house /Apartment,"18 GERALDINE ST, DUBLIN 7, DUBLIN, CO. DUBLIN",53.357662,-6.270328,high,address,"{""address_number"": ""matched"", ""street"": ""match...",POINT (-6.270328 53.357662),30.0,CABRA-GLASNEVIN

# Only keeping relevant columns

In [47]:
feature_cols = []

More will be added as we engineer features.

## Handling Binary Features

In [48]:
df['is_not_full_market_price'] = df.not_full_market_price.map({'No':0, 'Yes':1})

df['is_vat_exclusive'] = df.vat_exclusive.map({'No':0, 'Yes':1})

df['is_new'] = df['property_description'].map({
    'Second-Hand Dwelling house /Apartment': 0, 
    'New Dwelling house /Apartment': 1
})

df.head()

,date_of_sale,address,county,price,not_full_market_price,vat_exclusive,property_description,mapbox_query,latitude,longitude,confidence,feature_type,match_code,geometry,index_right,cso_lea,is_not_full_market_price,is_vat_exclusive,is_new
0,2016-02-29,"APT 14, RUSSELL COURT, FELTRIM RD",Dublin,118487.0,No,No,Second-Hand Dwelling house /Apartment,"RUSSELL COURT, FELTRIM RD, CO. DUBLIN",53.433318,-6.177927,none,street,{},POINT (-6.177927 53.433318),86.0,HOWTH-MALAHIDE,0,0,0
1,2016-07-08,"19 PARK VILLAS, DEMESNE RD, DUNDALK",Louth,222000.0,No,No,Second-Hand Dwelling house /Apartment,"19 PARK VILLAS, DEMESNE RD, DUNDALK, CO. LOUTH",54.003768,-6.406065,high,address,"{""address_number"": ""matched"", ""street"": ""match...",POINT (-6.406065 54.003768),66.0,DUNDALK-CARLINGFORD,0,0,0
2,2016-04-15,"No 2 The Grove, Cahereen Heights, Castleisland",Kerry,123348.0,No,Yes,New Dwelling house /Apartment,"THE GROVE, CAHEREEN HEIGHTS, CASTLEISLAND, CO....",52.221088,-9.468242,none,street,{},POINT (-9.468242 52.221088),43.0,CASTLEISLAND,0,1,1
3,2016-12-21,"APT 4 BLOCK 6, WOODFORD, WHEATON HALL",Louth,115000.0,No,No,Second-Hand Dwelling house /Apartment,"BLOCK 6, WOODFORD, WHEATON HALL, CO. LOUTH",53.050891,-8.399598,low,address,"{""address_number"": ""matched"", ""street"": ""unmat...",POINT (-8.399598 53.050891),109.0,LOUGHREA,0,0,0
4,2016-10-11,"18 GERALDINE ST, DUBLIN 7, DUBLIN",Dublin,225500.0,No,No,Second-Hand Dwelling house /Apartment,"18 GERALDINE ST, DUBLIN 7, DUBLIN, CO. DUBLIN",53.357662,-6.270328,high,address,"{""address_number"": ""matched"", ""street"": ""match...",POINT (-6.270328 53.357662),30.0,CABRA-GLASNEVIN,0,0,0

In [49]:
feature_cols += ['is_not_full_market_price', 'is_vat_exclusive', 'is_new']

## Handling date_of_sale

### Weekday

In [50]:
df['date_of_sale'] = pd.to_datetime(df['date_of_sale'])

df['day_of_week'] = df['date_of_sale'].dt.day_name().str.lower()

weekday_dummies = pd.get_dummies(
    df.day_of_week, 
    prefix='weekday',
    drop_first=True,
    dtype=int
)

# concatenate the dummy variable columns onto the original DataFrame (axis=0 means rows, axis=1 means columns)
df = pd.concat([df, weekday_dummies], axis=1)

### Month

In [51]:
df['sale_month'] = df['date_of_sale'].dt.month_name().str.lower()

month_dummies = pd.get_dummies(
    df['sale_month'], 
    prefix='month', 
    drop_first=True, 
    dtype=int        
)

df = pd.concat([df, month_dummies], axis=1)

### Year

In [52]:
df['sale_year'] = df['date_of_sale'].dt.year

In [53]:
feature_cols += weekday_dummies.columns.tolist()
feature_cols += month_dummies.columns.tolist()
feature_cols.append('sale_year')
display(feature_cols)

['is_not_full_market_price',
 'is_vat_exclusive',
 'is_new',
 'weekday_monday',
 'weekday_saturday',
 'weekday_sunday',
 'weekday_thursday',
 'weekday_tuesday',
 'weekday_wednesday',
 'month_august',
 'month_december',
 'month_february',
 'month_january',
 'month_july',
 'month_june',
 'month_march',
 'month_may',
 'month_november',
 'month_october',
 'month_september',
 'sale_year']

## Handling local electoral areas

In [54]:
lea_dummies = pd.get_dummies(
    df.cso_lea.str.lower(), 
    prefix='lea',
    drop_first=True,
    dtype=int
)

display(lea_dummies)

# concatenate the dummy variable columns onto the original DataFrame (axis=0 means rows, axis=1 means columns)
df = pd.concat([df, lea_dummies], axis=1)

,lea_ardee,lea_arklow,lea_artane-whitehall,lea_ashbourne,lea_athenry-oranmore,lea_athlone,lea_athy,lea_bailieborough-cootehill,lea_balbriggan,lea_ballina,...,lea_tramore-waterford city west,lea_trim,lea_tuam,lea_tullamore,lea_tullow,lea_waterford city east,lea_waterford city south,lea_westport,lea_wexford,lea_wicklow
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55435,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55436,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55437,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
55438,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55439,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [55]:
feature_cols += lea_dummies.columns.tolist()
display(feature_cols[-15:])

['lea_swords',
 'lea_tallaght central',
 'lea_tallaght south',
 'lea_thurles',
 'lea_tralee',
 'lea_tramore-waterford city west',
 'lea_trim',
 'lea_tuam',
 'lea_tullamore',
 'lea_tullow',
 'lea_waterford city east',
 'lea_waterford city south',
 'lea_westport',
 'lea_wexford',
 'lea_wicklow']

# Linear Regression

In [56]:
X = df[feature_cols]
y = df.price

# follow the usual sklearn pattern: import, instantiate, fit
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm.fit(X, y)

# print intercept and coefficients
print(lm.intercept_)
print(lm.coef_)

-34905658.73160785
[-9.84969022e+04  1.22269695e+04  1.91061597e+04 -7.66227210e+03
 -2.34694423e+03 -2.29826998e+04 -5.69122919e+03 -1.03746868e+04
 -1.04781673e+04  1.38449366e+04  1.56076008e+04 -4.74988267e+03
 -1.63655352e+02  1.58904763e+04  7.65085937e+03 -3.51472053e+03
 -3.63820125e+03  1.41903057e+04  1.00388617e+04  1.48035499e+04
  1.73800798e+04  1.85052510e+04  5.74757615e+04  1.74799862e+05
  1.00563892e+05  7.22188329e+04 -1.22489117e+04  2.30932974e+04
 -4.04697975e+04  1.59439218e+05 -6.09679724e+04 -5.87977121e+04
 -3.93060034e+04 -3.83410542e+04  1.04875345e+05 -2.61081106e+04
 -6.94202450e+04 -7.08966486e+04  1.13418860e+05  6.51203753e+04
  1.11551695e+05  4.74360391e+04 -6.45923724e+04 -3.16410551e+04
  4.83293493e+05  8.96905121e+04 -3.35804923e+04 -7.65593510e+04
  1.86892322e+05  2.76867337e+05 -5.68892895e+04  2.18360945e+05
 -4.41065709e+04  2.15332821e+04 -1.16957182e+04  1.24109863e+04
 -5.88898174e+04 -6.48112655e+04 -4.94543378e+04  2.16334091e+03
  8.41152615e+04 -2.28172814e+04 -1.15656188e+04  2.97337672e+03
 -4.85123249e+04  2.73293695e+05 -4.43355129e+04  1.32126230e+05
  7.55514427e+04 -4.62875480e+04  9.49195876e+04  6.57985950e+03
  3.05017670e+05  5.94387026e+04  3.88503439e+03  5.06972029e+04
  2.00704888e+04  6.47004124e+04  3.63147026e+04  5.52675555e+04
  1.37470976e+05  1.04314104e+05  1.67012421e+05 -5.03026455e+04
  3.80980555e+04  2.95167785e+04  1.47923027e+04 -9.44449251e+03
  3.40441844e+05  2.29105839e+04  4.25113758e+05 -1.22778774e+04
  1.81420153e+03 -3.19706835e+04  3.55980683e+03  1.88795861e+04
  2.08637859e+05  9.82259124e+04  3.95440394e+04  1.43617986e+05
  2.82902391e+05 -6.75004023e+04  3.87581968e+04  4.48272667e+04
  1.57568780e+04 -4.73964642e+04  2.51816871e+05  2.60812497e+05
 -3.42491551e+04  2.39196290e+04  4.10864639e+04  7.74076923e+04
  7.40324144e+04 -1.17364686e+04  3.55436126e+04  2.44267983e+05
  2.49040751e+04 -4.32265912e+04  3.60283719e+05 -7.75860639e+03
  6.61071175e+04  1.50871296e+05 -3.92544003e+04 -4.68725018e+04
  3.08851269e+04  7.96041598e+03  2.65923514e+04 -2.27449456e+04
 -3.73223439e+04 -4.79434351e+04  1.55491069e+04  1.38683143e+05
  5.57385107e+04  4.73869221e+02 -7.73693284e+04  1.53669064e+05
  3.45775914e+04 -3.11288316e+03  1.82208833e+02 -3.20837415e+04
 -2.61273729e+04  1.87821341e+04  1.16373930e+05  5.55169812e+04
 -1.59103792e+04 -2.42713099e+04  9.28100994e+04 -4.22323737e+04
  3.68362287e+04  1.61559705e+05  1.17745075e+05  8.97981174e+04
  5.68954707e+05 -4.77958222e+03 -9.00777723e+03  9.33231140e+03
  3.23485958e+05  1.37998455e+05 -6.24442838e+04 -4.46367974e+04
  2.16362270e+04  1.43444785e+05  1.79534657e+04  2.20932504e+04
 -4.23565957e+02 -2.71513468e+04  3.24525530e+05  1.64325020e+05
  4.98485901e+05 -8.87102447e+04  1.50245727e+05  7.76514252e+04
  6.63815276e+04 -3.74733355e+04 -2.49516905e+04 -8.76452732e+03
  7.69982237e+04 -1.42251150e+04  3.32071964e+03 -1.00201598e+04
  3.54658934e+04 -3.31172407e+04  2.55186075e+04 -2.46982856e+03
  1.29250245e+05]

In [59]:
lm.score(X, y)

0.3970984806196952

In [60]:
list(zip(feature_cols, lm.coef_))

[('is_not_full_market_price', np.float64(-98496.90223400501)),
 ('is_vat_exclusive', np.float64(12226.969472667668)),
 ('is_new', np.float64(19106.15966334904)),
 ('weekday_monday', np.float64(-7662.2720971273375)),
 ('weekday_saturday', np.float64(-2346.9442286483245)),
 ('weekday_sunday', np.float64(-22982.6998234552)),
 ('weekday_thursday', np.float64(-5691.229194559382)),
 ('weekday_tuesday', np.float64(-10374.68678137286)),
 ('weekday_wednesday', np.float64(-10478.167297281718)),
 ('month_august', np.float64(13844.93659119853)),
 ('month_december', np.float64(15607.600824485067)),
 ('month_february', np.float64(-4749.88266923331)),
 ('month_january', np.float64(-163.65535172152886)),
 ('month_july', np.float64(15890.476255058902)),
 ('month_june', np.float64(7650.859371057824)),
 ('month_march', np.float64(-3514.7205287973484)),
 ('month_may', np.float64(-3638.20125050511)),
 ('month_november', np.float64(14190.305740011725)),
 ('month_october', np.float64(10038.861676653141)),
 ('month_september', np.float64(14803.549855367088)),
 ('sale_year', np.float64(17380.079838402555)),
 ('lea_ardee', np.float64(18505.25095123335)),
 ('lea_arklow', np.float64(57475.761509075586)),
 ('lea_artane-whitehall', np.float64(174799.86227193676)),
 ('lea_ashbourne', np.float64(100563.89174631686)),
 ('lea_athenry-oranmore', np.float64(72218.83290395126)),
 ('lea_athlone', np.float64(-12248.911675435578)),
 ('lea_athy', np.float64(23093.29741297575)),
 ('lea_bailieborough-cootehill', np.float64(-40469.7974920072)),
 ('lea_balbriggan', np.float64(159439.21751161985)),
 ('lea_ballina', np.float64(-60967.97235477852)),
 ('lea_ballinamore', np.float64(-58797.712125965554)),
 ('lea_ballinasloe', np.float64(-39306.00342242307)),
 ('lea_ballybay-clones', np.float64(-38341.05415381947)),
 ('lea_ballyfermot-drimnagh', np.float64(104875.34519572719)),
 ('lea_ballyjamesduff', np.float64(-26108.110583194648)),
 ('lea_ballymahon', np.float64(-69420.24497487131)),
 ('lea_ballymote-tobercurry', np.float64(-70896.64857259105)),
 ('lea_ballymun-finglas', np.float64(113418.86021368082)),
 ('lea_baltinglass', np.float64(65120.37525321093)),
 ('lea_bandon-kinsale', np.float64(111551.69490640503)),
 ('lea_bantry-west cork', np.float64(47436.0391280357)),
 ('lea_belmullet', np.float64(-64592.37242755016)),
 ('lea_birr', np.float64(-31641.055105262778)),
 ('lea_blackrock', np.float64(483293.492718093)),
 ('lea_blanchardstown-mulhuddart', np.float64(89690.51213242905)),
 ('lea_borris-in-ossory-mountmellick', np.float64(-33580.492278270605)),
 ('lea_boyle', np.float64(-76559.35097936752)),
 ('lea_bray east', np.float64(186892.32187529976)),
 ('lea_bray west', np.float64(276867.337170063)),
 ('lea_buncrana', np.float64(-56889.28953660214)),
 ('lea_cabra-glasnevin', np.float64(218360.9452258871)),
 ('lea_cahir', np.float64(-44106.570919386926)),
 ('lea_callan-thomastown', np.float64(21533.28206364214)),
 ('lea_cappamore-kilmallock', np.float64(-11695.718225447854)),
 ('lea_carlow', np.float64(12410.986312495967)),
 ('lea_carndonagh', np.float64(-58889.81743721183)),
 ('lea_carrick-on-shannon', np.float64(-64811.265474272484)),
 ('lea_carrick-on-suir', np.float64(-49454.33782369632)),
 ('lea_carrickmacross-castleblayney', np.float64(2163.3409076386597)),
 ('lea_carrigaline', np.float64(84115.2615434627)),
 ('lea_cashel-tipperary', np.float64(-22817.281368934884)),
 ('lea_castlebar', np.float64(-11565.618833161134)),
 ('lea_castlecomer', np.float64(2973.3767233846374)),
 ('lea_castleisland', np.float64(-48512.32490165315)),
 ('lea_castleknock', np.float64(273293.6954667498)),
 ('lea_cavan-belturbet', np.float64(-44335.512865786906)),
 ('lea_celbridge', np.float64(132126.23030491167)),
 ('lea_clane', np.float64(75551.44271361858)),
 ('lea_claremorris', np.float64(-46287.54796231276)),
 ('lea_clondalkin', np.float64(94919.58758256029)),
 ('lea_clonmel', np.float64(6579.859502870422)),
 ('lea_clontarf', np.float64(305017.66985009157)),
 ('lea_cobh', np.float64(59438.7026208802)),
 ('lea_conamara north', np.float64(3885.0343900497755)),
 ('lea_conamara south', np.float64(50697.20286047715)),
 ('lea_corca dhuibhne', np.float64(20070.488826286382)),
 ('lea_cork city north east', np.float64(64700.412383011295)),
 ('lea_cork city north west', np.float64(36314.70257920629)),
 ('lea_cork city south central', np.float64(55267.55545717258)),
 ('lea_cork city south east', np.float64(137470.9761383728)),
 ('lea_cork city south west', np.float64(104314.10430063636)),
 ('lea_donaghmede', np.float64(167012.42057518195)),
 ('lea_donegal', np.float64(-50302.645531996066)),
 ('lea_drogheda rural', np.float64(38098.05547352899)),
 ('lea_drogheda urban', np.float64(29516.778494090366)),
 ('lea_dundalk south', np.float64(14792.302707040013)),
 ('lea_dundalk-carlingford', np.float64(-9444.492505429887)),
 ('lea_dundrum', np.float64(340441.8439942556)),
 ('lea_dungarvan', np.float64(22910.58394755787)),
 ('lea_dún laoghaire', np.float64(425113.7583199257)),
 ('lea_edenderry', np.float64(-12277.877408292363)),
 ('lea_ennis', np.float64(1814.2015313996162)),
 ('lea_enniscorthy', np.float64(-31970.683469071344)),
 ('lea_ennistimon', np.float64(3559.8068251259538)),
 ('lea_fermoy', np.float64(18879.58611183664)),
 ('lea_firhouse-bohernabreena', np.float64(208637.85894081887)),
 ('lea_galway city central', np.float64(98225.91240300212)),
 ('lea_galway city east', np.float64(39544.039441252025)),
 ('lea_galway city west', np.float64(143617.98642667162)),
 ('lea_glencullen-sandyford', np.float64(282902.3905994703)),
 ('lea_glenties', np.float64(-67500.40232458827)),
 ('lea_gorey', np.float64(38758.19683090159)),
 ('lea_gort-kinvara', np.float64(44827.2666889909)),
 ('lea_graiguecullen-portarlington', np.float64(15756.878022050387)),
 ('lea_granard', np.float64(-47396.46422786494)),
 ('lea_greystones', np.float64(251816.87124035225)),
 ('lea_howth-malahide', np.float64(260812.4970406965)),
 ('lea_kanturk', np.float64(-34249.15505738091)),
 ('lea_kells', np.float64(23919.628989177254)),
 ('lea_kenmare', np.float64(41086.46392133333)),
 ('lea_kildare', np.float64(77407.69225373158)),
 ('lea_kilkenny', np.float64(74032.41436502959)),
 ('lea_killaloe', np.float64(-11736.468638159698)),
 ('lea_killarney', np.float64(35543.61259683719)),
 ('lea_killiney-shankill', np.float64(244267.98313950884)),
 ('lea_kilmuckridge', np.float64(24904.075097905145)),
 ('lea_kilrush', np.float64(-43226.591152445966)),
 ('lea_kimmage-rathmines', np.float64(360283.7187827936)),
 ('lea_kinnegad', np.float64(-7758.606387967375)),
 ('lea_laytown-bettystown', np.float64(66107.11747920956)),
 ('lea_leixlip', np.float64(150871.29642196867)),
 ('lea_letterkenny', np.float64(-39254.40028732835)),
 ('lea_lifford-stranorlar', np.float64(-46872.50176506817)),
 ('lea_limerick city east', np.float64(30885.126915989415)),
 ('lea_limerick city north', np.float64(7960.415976109129)),
 ('lea_limerick city west', np.float64(26592.351362432102)),
 ('lea_lismore', np.float64(-22744.945550043507)),
 ('lea_listowel', np.float64(-37322.3438706179)),
 ('lea_longford', np.float64(-47943.43511627837)),
 ('lea_loughrea', np.float64(15549.10691739533)),
 ('lea_lucan', np.float64(138683.14322331757)),
 ('lea_macroom', np.float64(55738.510688315706)),
 ('lea_mallow', np.float64(473.86922069036154)),
 ('lea_manorhamilton', np.float64(-77369.32841952884)),
 ('lea_maynooth', np.float64(153669.06412108234)),
 ('lea_midleton', np.float64(34577.59143675388)),
 ('lea_milford', np.float64(-3112.8831551946205)),
 ('lea_moate', np.float64(182.20883258315007)),
 ('lea_monaghan', np.float64(-32083.741519622785)),
 ('lea_muinebeag', np.float64(-26127.372929874808)),
 ('lea_mullingar', np.float64(18782.134086793514)),
 ('lea_naas', np.float64(116373.9300924097)),
 ('lea_navan', np.float64(55516.9812265243)),
 ('lea_nenagh', np.float64(-15910.379226530938)),
 ('lea_new ross', np.float64(-24271.309908609)),
 ('lea_newbridge', np.float64(92810.09937182584)),
 ('lea_newcastle west', np.float64(-42232.37373382867)),
 ('lea_newport', np.float64(36836.22870676468)),
 ('lea_north inner city', np.float64(161559.70522935648)),
 ('lea_ongar', np.float64(117745.07459430322)),
 ('lea_palmerstown-fonthill', np.float64(89798.11741296733)),
 ('lea_pembroke', np.float64(568954.7073150513)),
 ('lea_piltown', np.float64(-4779.582218151016)),
 ('lea_portlaoise', np.float64(-9007.77723090211)),
 ('lea_portlaw-kilmacthomas', np.float64(9332.311403989297)),
 ('lea_rathfarnham-templeogue', np.float64(323485.9575557088)),
 ('lea_ratoath', np.float64(137998.45524071885)),
 ('lea_roscommon', np.float64(-62444.28377893871)),
 ('lea_roscrea-templemore', np.float64(-44636.797428307415)),
 ('lea_rosslare', np.float64(21636.22700806646)),
 ('lea_rush-lusk', np.float64(143444.78472642967)),
 ('lea_shannon', np.float64(17953.465703780283)),
 ('lea_skibbereen-west cork', np.float64(22093.250350838447)),
 ('lea_sligo-drumcliff', np.float64(-423.5659569805721)),
 ('lea_sligo-strandhill', np.float64(-27151.346753506034)),
 ('lea_south east inner city', np.float64(324525.529740659)),
 ('lea_south west inner city', np.float64(164325.0197293951)),
 ('lea_stillorgan', np.float64(498485.9011699179)),
 ('lea_swinford', np.float64(-88710.24472444103)),
 ('lea_swords', np.float64(150245.72735554347)),
 ('lea_tallaght central', np.float64(77651.42522779587)),
 ('lea_tallaght south', np.float64(66381.52763677905)),
 ('lea_thurles', np.float64(-37473.33552406847)),
 ('lea_tralee', np.float64(-24951.69048756746)),
 ('lea_tramore-waterford city west', np.float64(-8764.527323202827)),
 ('lea_trim', np.float64(76998.22370003004)),
 ('lea_tuam', np.float64(-14225.114956374957)),
 ('lea_tullamore', np.float64(3320.719636016329)),
 ('lea_tullow', np.float64(-10020.15983118293)),
 ('lea_waterford city east', np.float64(35465.89337863923)),
 ('lea_waterford city south', np.float64(-33117.240725078766)),
 ('lea_westport', np.float64(25518.607518030563)),
 ('lea_wexford', np.float64(-2469.828559228583)),
 ('lea_wicklow', np.float64(129250.24455880401))]

In [64]:
lower = y.quantile(0)
upper = y.quantile(1)

print(f"Clamped lower: €{lower:,.0f}")
print(f"Clamped upper: €{upper:,.0f}")
print(f"At lower bound: {(y == lower).sum()}")
print(f"At upper bound: {(y == upper).sum()}")

Clamped lower: €5,260
Clamped upper: €1,426,515
At lower bound: 1
At upper bound: 551